In [3]:
import tensorflow as tf

In [5]:
!pip install pandas


In [6]:
!pip install numpy

In [8]:
!pip install matplotlib


In [9]:
!pip install scikit-learn

  Using cached scikit_learn-0.24.0-cp37-cp37m-win_amd64.whl (6.8 MB)
  Using cached joblib-1.0.0-py3-none-any.whl (302 kB)
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)


In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
### Vocabulary size
voc_size=10000

#### One hot representation

In [15]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5342, 6047, 3702, 4913], [5342, 6047, 3702, 3351], [5342, 9482, 3702, 6504], [6556, 9585, 1264, 7440, 4214], [6556, 9585, 1264, 7440, 6008], [2866, 5342, 1471, 3702, 3292], [7825, 3579, 875, 7440]]


#### Word embedding representation

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [18]:
import numpy as np

In [19]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5342 6047 3702 4913]
 [   0    0    0    0 5342 6047 3702 3351]
 [   0    0    0    0 5342 9482 3702 6504]
 [   0    0    0 6556 9585 1264 7440 4214]
 [   0    0    0 6556 9585 1264 7440 6008]
 [   0    0    0 2866 5342 1471 3702 3292]
 [   0    0    0    0 7825 3579  875 7440]]


In [20]:
dim=10

In [22]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(embedded_docs))

[[[-4.29478884e-02  3.85510586e-02  1.73803307e-02  3.34631838e-02
   -2.27553248e-02 -1.45891085e-02  3.25861312e-02 -4.31898236e-02
   -3.95607948e-03 -3.53537872e-03]
  [-4.29478884e-02  3.85510586e-02  1.73803307e-02  3.34631838e-02
   -2.27553248e-02 -1.45891085e-02  3.25861312e-02 -4.31898236e-02
   -3.95607948e-03 -3.53537872e-03]
  [-4.29478884e-02  3.85510586e-02  1.73803307e-02  3.34631838e-02
   -2.27553248e-02 -1.45891085e-02  3.25861312e-02 -4.31898236e-02
   -3.95607948e-03 -3.53537872e-03]
  [-4.29478884e-02  3.85510586e-02  1.73803307e-02  3.34631838e-02
   -2.27553248e-02 -1.45891085e-02  3.25861312e-02 -4.31898236e-02
   -3.95607948e-03 -3.53537872e-03]
  [ 1.24885552e-02  4.07984741e-02  3.38990726e-02  5.80413267e-03
   -4.85772602e-02 -5.31003624e-03  2.42800228e-02  4.83622812e-02
   -4.21544686e-02 -6.66253641e-03]
  [ 7.80488178e-03 -1.64736621e-02  4.90612499e-02 -1.15640089e-03
    3.21274064e-02 -4.00217548e-02 -1.96844228e-02  1.84013285e-02
    7.58992508e-

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 5342, 6047, 3702, 4913])

In [26]:
print(model.predict(embedded_docs)[0])

[[-0.04294789  0.03855106  0.01738033  0.03346318 -0.02275532 -0.01458911
   0.03258613 -0.04318982 -0.00395608 -0.00353538]
 [-0.04294789  0.03855106  0.01738033  0.03346318 -0.02275532 -0.01458911
   0.03258613 -0.04318982 -0.00395608 -0.00353538]
 [-0.04294789  0.03855106  0.01738033  0.03346318 -0.02275532 -0.01458911
   0.03258613 -0.04318982 -0.00395608 -0.00353538]
 [-0.04294789  0.03855106  0.01738033  0.03346318 -0.02275532 -0.01458911
   0.03258613 -0.04318982 -0.00395608 -0.00353538]
 [ 0.01248856  0.04079847  0.03389907  0.00580413 -0.04857726 -0.00531004
   0.02428002  0.04836228 -0.04215447 -0.00666254]
 [ 0.00780488 -0.01647366  0.04906125 -0.0011564   0.03212741 -0.04002175
  -0.01968442  0.01840133  0.00758993  0.00869163]
 [ 0.01025409  0.0394832   0.0322224  -0.00855789  0.01201993  0.01866743
  -0.01414565 -0.00853081  0.0165686   0.02307797]
 [-0.02424003  0.01582493 -0.02477865  0.02067113  0.03580544 -0.02473086
   0.01474505 -0.03019197  0.03617101  0.03166125]]